version: v1.2.0

dsn: memory

serve:
  public:
    base_url: http://127.0.0.1:4433/
    cors:
      enabled: true
  admin:
    base_url: http://127.0.0.1:4434/

selfservice:
  flows:
    error:
      ui_url: http://127.0.0.1:4455/error

    settings:
      ui_url: http://127.0.0.1:4455/settings
      privileged_session_max_age: 15m
      required_aal: aal1

    recovery:
      enabled: true
      ui_url: http://127.0.0.1:4455/recovery
      use: code

    verification:
      enabled: true
      ui_url: http://127.0.0.1:4455/verification
      use: code
      after:
        default_browser_return_url: http://127.0.0.1:4455/

    logout:
      after:
        default_browser_return_url: http://127.0.0.1:4455/login

    login:
      ui_url: http://127.0.0.1:4455/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: http://127.0.0.1:4455/registration
      after:
        password:
          hooks:
            - hook: session
            - hook: show_verification_ui

  default_browser_return_url: http://127.0.0.1:4455/welcome
  allowed_return_urls:
    - http://127.0.0.1:4455
    - http://localhost:19006/Callback
    - exp://localhost:8081/--/Callback

  methods:
    password:
      enabled: true
      config:
        haveibeenpwned_enabled: false
    totp:
      config:
        issuer: Kratos
      enabled: true
    lookup_secret:
      enabled: true
    link:
      enabled: true
    code:
      enabled: true
    oidc:
      enabled: true
      config:
        providers:
          - id: thai-d
            provider: generic
            client_id: THAID-CLIENT-ID
            client_secret: THAID-CLIENT-SECRET
            issuer_url: THAID-ISSUER-URL
            auth_url: THAID-AUTH-URL
            token_url: THAID-TOKEN-URL
            mapper_url: file://path/to/oidc.jsonnet
        base_redirect_uri: THAID-REDIRECT-URI

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
  cipher:
    - 32-LONG-SECRET-NOT-SECURE-AT-ALL

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

courier:
  delivery_strategy: http
  http:
    request_config:
      url: https://api.sendgrid.com/v3/mail/send
      method: POST
      body: base64://BASE-64-JSONNET-PERSONALIZED-TO-MATCH-SENDGRID-BODY
      headers:
        'Content-Type': 'application/json'
      auth:
        type: api_key
        config:
          name: Authorization
          value: Bearer YOUR-SENDGRID-API-KEY
          in: header

feature_flags:
  use_continue_with_transitions: true
